### ISSUE TITLE
Incluir gráfica en el Dashboard

### ISSUE THREAD

**Issue by JRafael91** [JRafael91/auto-portal#12]
Incluir gráfica que muestre el total de órdenes generadas.

### Tareas
- [x] Desarrollar vista de Dashboard.
- [x]  Gráfica de barra con el total de órdenes generadas.

**Comment by JRafael91** [comment]
Captura de pantallas.



![Image](https://github.com/JRafael91/auto-portal/assets/39107286/919aa6c7-0147-45a0-a145-13771c1020fc)

**Comment by ivanchenoweth** [comment]
Felicidades. Muy buen trabajo
