### ISSUE TITLE
Módulo de usuarios

### ISSUE THREAD

**Issue by JRafael91** [JRafael91/auto-portal#3]
Se requiere desarrollar un módulo de usuarios, que permita la gestión integral de los usuarios. Este módulo debe incluir las funcionalidades de registro, actualizar, eliminar, así como tal la vista de usuarios.

#### Tareas
- [x] Vista de usuarios.
- [x] CRUD usuarios.

**Comment by JRafael91** [comment]
Capturas de módulo de usuarios


![Image](https://github.com/JRafael91/auto-portal/assets/39107286/e60c0a87-6a2f-4ac6-8fe6-281cd26c64d4)



![Image](https://github.com/JRafael91/auto-portal/assets/39107286/2c635d8e-b7c9-4e57-8876-c8eeae66251f)



![Image](https://github.com/JRafael91/auto-portal/assets/39107286/f7cac4da-f9b4-4615-bedb-ff2c1b6f296b)



![Image](https://github.com/JRafael91/auto-portal/assets/39107286/7a3c686c-7850-4dda-8580-72da373c206d)

**Comment by ivanchenoweth** [comment]
Excelente. Buena evidencia
